---

- hosts: localhost
  connection: local

  vars:
    homebrew_taps:
      - homebrew/core
      - homebrew/cask
    homebrew_installed_packages:
      - bash
      - git
      - mas
      - ssh-copy-id
      - the_silver_searcher
      - trash
      - vim
      - zsh
    homebrew_cask_apps:
      - hyper
    osx_defaults:
          # allow keyrepeat
          - domain: 'co.zeit.hyper'
            key: 'ApplePressAndHoldEnabled'
            type: boolean
            value: false

  pre_tasks:
    - import_role:
        name: ansible-role-homebrew
    - import_role:
        name: roderik.superlumic-osx-defaults

  tasks:
    - name: create ssh directory
      file:
        path: "{{item}}"
        state: directory
        mode: 0700
      with_items:
        - ~/.ssh
    - name: personal ssh config
      copy:
        src: files/ssh_config
        dest: ~/.ssh/config
    - name: pull vim-prefs
      git:
        repo: github-personal:dovdor/vim-prefs.git
        dest: ~/Projects/personal/vim-prefs
        update: yes
    - name: remove current vim configuration
      file:
        path: "~/{{ item }}"
        state: absent
      with_items:
        - .vim
    - name: link vim configuration
      file:
        src: "~/Projects/personal/vim-prefs/{{ item }}"
        dest: "~/{{ item }}"
        state: link
      with_items:
        - .vim
        - .vimrc
        - .vimspelladdition.add
    - name: pull shell-prefs
      git:
          repo: github-personal:dovdor/shell-prefs.git
          dest: ~/Projects/personal/shell-prefs
          update: yes
    - name: install ohmyzsh
      file:
        src: "~/Projects/personal/shell-prefs/{{ item }}"
        dest: "~/{{ item }}"
        state: link
      with_items:
        - .zshrc
        - .oh-my-zsh
        - .oh-my-zsh-custom
    - name: zsh by default
      shell: chsh -s /usr/local/bin/zsh {{ lookup('env', 'USER') }}
      become: yes
